"""empty message

Revision ID: 00007ddd789f
Revises: 311a65754783
Create Date: 2018-11-30 17:10:05.584629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00007ddd789f'
down_revision = '311a65754783'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Error message: can't add a not null column with default value NULL
    # Update to remove not null constraint
    # op.add_column('products', sa.Column('product_code', sa.String(), nullable=False))
    op.add_column('products', sa.Column('product_code', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'products', ['product_code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_column('products', 'product_code')
    # ### end Alembic commands ###
